export const GET_PRODUCT_REQUEST = 'GET_PRODUCT_REQUEST'
export const GET_PRODUCT_SUCCESS = 'GET_PRODUCT_SUCCESS'
export const GET_PRODUCT_FAIL = 'GET_PRODUCT_FAIL'

export const GET_PRODUCT_INFO_REQUEST = 'GET_PRODUCT_INFO_REQUEST'
export const GET_PRODUCT_INFO_SUCCESS = 'GET_PRODUCT_INFO_SUCCESS'
export const GET_PRODUCT_INFO_FAIL = 'GET_PRODUCT_INFO_FAIL'
